# .github/workflows/production.yml
name: Vercel Production Deployment

# Run on push to main OR PRs targeting main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN:     ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel (production)
        # run vercel deploy in your frontend folder
        working-directory: frontend
        run: |
          # Pull existing project settings
          vercel pull --yes \
            --org $VERCEL_ORG_ID \
            --project $VERCEL_PROJECT_ID \
            --environment=production \
            --token $VERCEL_TOKEN

          # Build and deploy
          vercel build --prod --token $VERCEL_TOKEN
          vercel deploy --prebuilt --prod --token $VERCEL_TOKEN
